export const LOAD_PRODUCTS_BEGIN = 'LOAD_PRODUCTS_BEGIN';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';
export const SINGLE_PRODUCTS_BEGIN = 'SINGLE_PRODUCTS_BEGIN';
export const SINGLE_PRODUCTS_SUCCESS = 'SINGLE_PRODUCTS_SUCCESS';
export const SINGLE_PRODUCTS_ERROR = 'SINGLE_PRODUCTS_ERROR';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
